import {
	compareStrIterator,
	binarySearch,
	searchRange,
	shipWithinDays,
	minEatingSpeed,
	removeDuplicates,
	removeElement,
	moveZeroes,
	reverseString,
	longestPalindrome,
	minWindow,
	checkInclusion,
	findAnagrams,
	lengthOfLongestSubstring,
	advantageCount,
	mergeTwoLists,
	partition,
	removeNthFromEnd,
	middleNode,
	detectCycle,
	getIntersectionNode,
	reverseListIteration,
	reverseListRecursion,
	reverseBetweenIteration,
	reverseBetweenRecursion,
	reverseKGroup,
	isPalindrome,
	isValid,
	minAddToMakeValid,
	minInsertions,
	nextGreaterElement,
	dailyTemperatures,
	nextGreaterElements,
	maxSlidingWindow,
	removeDuplicateLetters,
	maxDepthBack,
	maxDepthDp,
} from '@/algorithm'
import {
	deepCopy,
	myCall,
	myApply,
	myBind,
	flatArray,
	memoFunc,
	curryFunc,
	flatObj,
	exampleReflectProxy,
	exampleReflectOwnKeys,
	myNew,
	myInstanceOf,
} from '@/scene'

console.log(
	'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ algorithm ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~',
)
compareStrIterator()
binarySearch()
searchRange()
shipWithinDays()
minEatingSpeed()
removeDuplicates()
removeElement()
moveZeroes()
reverseString()
longestPalindrome()
minWindow()
checkInclusion()
findAnagrams()
lengthOfLongestSubstring()
advantageCount()
mergeTwoLists()
partition()
removeNthFromEnd()
middleNode()
detectCycle()
getIntersectionNode()
reverseListIteration()
reverseListRecursion()
reverseBetweenIteration()
reverseBetweenRecursion()
reverseKGroup()
isPalindrome()
isValid()
minAddToMakeValid()
minInsertions()
nextGreaterElement()
dailyTemperatures()
nextGreaterElements()
maxSlidingWindow()
removeDuplicateLetters()
maxDepthBack()
maxDepthDp()

console.log(
	'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ scene ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~',
)
deepCopy()
myCall()
myApply()
myBind()
flatArray()
flatObj()
memoFunc()
curryFunc()
exampleReflectProxy()
exampleReflectOwnKeys()
myNew()
myInstanceOf()
